GET http://127.0.0.1:5000/api/hello
Accept: application/json
X-TenantId: tenant10

###

GET http://localhost:5000/api/hello
Accept: application/json
X-TenantId: tenant1

###

GET http://localhost:5000/api/hello
Accept: application/json
Host: tenant0.example.com

###
